name: EVerest CI/CD

on:
  push:
    branches:
      - CI_CD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential git \
            libboost-all-dev libssl-dev libsqlite3-dev \
            libcurl4-openssl-dev pkg-config \
            libsystemd-dev libudev-dev \
            libpcap-dev

      - name: Build EVerest
        run: |
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)
